language: php

before_script:
    - sudo apt-get install -y check
    - git clone git@github.com:lstrojny/nanotime.git
    - cd nanotime && ./autogen.sh && make && make install
    - phpize
    - ./configure --with-libnanotime-prefix=/usr/local
    - make

script:
    - make test
    - sh test-report.sh

notifications:
  email:
    - lars@strojny.net
